-- 1
SELECT TURNIEJ.Nazwa AS Turniej, POLE_GOLFOWE.Nazwa AS Pole_Golfowe, STATUS.Nazwa AS Status_Pola, PRACOWNIK.Imie ||' '|| PRACOWNIK.Nazwisko AS Organizator
FROM TURNIEJ
JOIN POLE_GOLFOWE ON TURNIEJ.POLE_GOLFOWE_ID = POLE_GOLFOWE.ID
JOIN STATUS ON POLE_GOLFOWE.STATUS_ID = STATUS.ID
JOIN PRACOWNIK ON TURNIEJ.ORGANIZATOR_ID = PRACOWNIK.ID
WHERE STATUS.Nazwa = 'W konserwacji';

-- 2
SELECT Imie, Nazwisko, Email
FROM CZLONEK
WHERE ID IN (
    SELECT Czlonek_ID
    FROM WYPOZYCZENIE_SPRZETU
    )
AND ID NOT IN (
    SELECT Czlonek_ID
    FROM REZERWACJA
    );

--3
SELECT CZLONEK.Imie, CZLONEK.Nazwisko, COUNT(UCZESNICTWO_TURNIEJ.Turniej_ID) AS Liczba_Tueniejow
FROM CZLONEK
JOIN UCZESNICTWO_TURNIEJ ON Czlonek.ID = UCZESNICTWO_TURNIEJ.Czlonek_ID
GROUP BY CZLONEK.Imie, CZLONEK.Nazwisko
HAVING COUNT(UCZESNICTWO_TURNIEJ.Turniej_ID) > 1;

--4
SELECT PRACOWNIK.Imie, PRACOWNIK.Nazwisko, PRACOWNIK.Pensja, STANOWISKO.Nazwa
FROM PRACOWNIK
JOIN STANOWISKO ON PRACOWNIK.Stanowisko_ID = STANOWISKO.ID
WHERE PRACOWNIK.Pensja > (
    SELECT AVG(P1.Pensja)
    FROM PRACOWNIK P1
    WHERE P1.STANOWISKO_ID = PRACOWNIK.STANOWISKO_ID
    );

--5
SELECT SPRZET_GOLFOWY.Nazwa, PRACOWNIK.Imie ||' '|| PRACOWNIK.Nazwisko AS Recepcjonista, COUNT(WYPOZYCZENIE_SPRZETU.ID) AS Liczba_Wypozyczen
FROM WYPOZYCZENIE_SPRZETU
JOIN SPRZET_GOLFOWY ON WYPOZYCZENIE_SPRZETU.Sprzet_Golfowy_ID = SPRZET_GOLFOWY.ID
JOIN PRACOWNIK ON WYPOZYCZENIE_SPRZETU.Pracownik_ID = PRACOWNIK.ID
JOIN STANOWISKO ON PRACOWNIK.Stanowisko_ID = STANOWISKO.ID
WHERE STANOWISKO.Nazwa = 'Recepcjonista'
GROUP BY SPRZET_GOLFOWY.Nazwa, PRACOWNIK.Imie ||' '|| PRACOWNIK.Nazwisko;

--6 Ile rezerwacji miało każde pole i ile łącznie godzin gracze na nim spędzili
SELECT POLE_GOLFOWE.Nazwa AS Pole_Golfowe, STATUS.Nazwa AS Obecny_Status, COUNT(REZERWACJA.ID) AS Liczba_Rezerwacji, NVL(SUM((Rezerwacja.DataEnd - Rezerwacja.DataStart)*24),0) AS Laczny_Czas_Gry
FROM POLE_GOLFOWE
JOIN STATUS ON POLE_GOLFOWE.Status_ID = STATUS.ID
LEFT JOIN REZERWACJA ON POLE_GOLFOWE.ID = REZERWACJA.POLE_GOLFOWE_ID
GROUP BY POLE_GOLFOWE.Nazwa, STATUS.Nazwa;

-- 7. Klient z najnowszą rezerwacją pola w systemie
SELECT CZLONEK.Imie AS Imie, CZLONEK.Nazwisko AS Nazwisko, POLE_GOLFOWE.Nazwa AS Pole_Golfowe, REZERWACJA.DataStart AS Data_Rezerwacji
FROM REZERWACJA
JOIN CZLONEK ON REZERWACJA.Czlonek_ID = CZLONEK.ID
JOIN POLE_GOLFOWE ON REZERWACJA.Pole_Golfowe_ID = POLE_GOLFOWE.ID
WHERE REZERWACJA.DataStart = (
    SELECT MAX(R1.DataStart)
    FROM REZERWACJA R1
    );

